directories:
  output: dist_electron
  buildResources: build
appId: com.assopilot.app
productName: AssoPilot
files:
  - filter:
      - dist/asso-pilot/**/*
      - electron/main.js
      - electron/preload.js
      - package.json
extraResources:
  - from: src/assets/
    to: assets/
    filter:
      - '**/*'
win:
  target: nsis
  icon: src/assets/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 38.4.0
